### ISSUE TITLE
Commit d3f4248 removes Linux compatibility

### ISSUE THREAD

**Issue by ghalfacree** [chebykinn/sedmario#4]
Commit d3f4248 breaks the software when run under Linux: `-S` is required in order to pass options in a shebang line.

# Repro:
Run `./mario.sh`

# Expected result:
You play a sed-driven version of Super Mario Bros.

# Actual result:
 ```
press q to exit
/usr/bin/env: 'sed -Enf': No such file or directory
/usr/bin/env: use -[v]S to pass options in shebang lines
```

# Fix (for Linux, anyway):
Revert d3f4248.

**Comment by chebykinn** [comment]
If it works, don't fix it
Reverted :)
